
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author usuario
 */
public class Cambiasletras extends javax.swing.JFrame {

    /**
     * Creates new form DATOS
     */
    public Cambiasletras() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Cambiasletras");
        ///CODIGO PARA IMAGEN DE FONDO////
((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Imagen/FONDOS.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblvocales = new javax.swing.JLabel();
        lblfrace = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblE = new javax.swing.JLabel();
        txtoracion = new javax.swing.JTextField();
        txtcambiar = new javax.swing.JTextField();
        txtalrevez = new javax.swing.JTextField();
        btnvalidar = new javax.swing.JButton();
        lblE1 = new javax.swing.JLabel();
        txtNUM = new javax.swing.JTextField();
        lblE2 = new javax.swing.JLabel();
        txtespacios = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtvocales = new javax.swing.JTextArea();
        lblE3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblvocales.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblvocales.setText("REEMPLAZAR LETRAS");

        lblfrace.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblfrace.setText("INGRESAR ORACION O PALABRA :");

        lblA.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblA.setText("ORACION O PALABRA CAMBIADA : ");

        lblE.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblE.setText("ORACION O PLABRA ALREVEZ :");

        txtoracion.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        txtcambiar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtcambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcambiarActionPerformed(evt);
            }
        });

        txtalrevez.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        btnvalidar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnvalidar.setText("COMPROBAR");
        btnvalidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvalidarActionPerformed(evt);
            }
        });

        lblE1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblE1.setText("NUMERO DE PALABRAS :");

        txtNUM.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        lblE2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblE2.setText("NUMERO DE ESPACIOS :");

        txtespacios.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        txtvocales.setColumns(20);
        txtvocales.setRows(5);
        jScrollPane1.setViewportView(txtvocales);

        lblE3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblE3.setText("NUMERO DE VOCALES :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblfrace)
                                        .addComponent(lblA))
                                    .addGap(23, 23, 23))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblE3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblE, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblE2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblE1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtoracion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(txtcambiar)
                                .addComponent(txtalrevez)
                                .addComponent(txtNUM, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtespacios, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnvalidar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(lblvocales)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblvocales)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblfrace)
                    .addComponent(txtoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA)
                    .addComponent(txtcambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblE)
                    .addComponent(txtalrevez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblE1)
                    .addComponent(txtNUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblE2)
                    .addComponent(txtespacios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblE3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnvalidar)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcambiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcambiarActionPerformed

    private void btnvalidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalidarActionPerformed
        // Obtener el texto ingresado en el componente de texto llamado "txtoracion"
        String frase = txtoracion.getText();

        // Crear un StringBuilder para almacenar la frase modificada
        StringBuilder frace2 = new StringBuilder();

        // Variables para contar espacios y palabras
        int Espacios = 0; // Inicializar contador de espacios
        int Palabras = 0; // Inicializar contador de palabras
        boolean numpalabras = false; // Variable para rastrear si estamos dentro de una palabra o no

        // Recorrer cada caracter de la frase original
        for (int i = 0; i < frase.length(); i++) {
            char letra = Character.toLowerCase(frase.charAt(i)); // Obtener el carácter en la posición actual y convertir a minúsculas

            // Contar espacios y palabras
            if (letra == ' ') {
                Espacios++; // Incrementar el contador de espacios
                numpalabras = false; // Estamos fuera de una palabra cuando encontramos un espacio
            } else {
                if (!numpalabras) {
                    Palabras++; // Incrementar el contador de palabras si estamos al comienzo de una palabra
                    numpalabras = true; // Estamos dentro de una palabra
                }
            }

            // Verificar si el caracter es 'o' y reemplazarlo por '$'
            if (letra == 'o') {
                frace2.append('$'); // Agregar '$' al StringBuilder si el carácter es 'o'
            } // Verificar si el caracter es 'a' y reemplazarlo por '@'
            else if (letra == 'a') {
                frace2.append('@'); // Agregar '@' al StringBuilder si el carácter es 'a'
            } // Mantener el caracter original si no es 'o' ni 'a'
            else {
                frace2.append(letra); // Agregar el carácter original al StringBuilder
            }
        }

        // Crear un StringBuilder para construir la cadena al revés manualmente
        StringBuilder reversa = new StringBuilder();

        // Recorrer la longitud de la frase original en sentido inverso
        for (int i = frase.length() - 1; i >= 0; i--) {
            // Agregar cada caracter al nuevo StringBuilder en orden inverso
            reversa.append(frase.charAt(i));
        }

        // Mostrar el resultado de la frase modificada en el componente "txtcambiar"
        txtcambiar.setText(frace2.toString());

        // Mostrar el resultado de la frase al revés en el componente "txtalrevez"
        txtalrevez.setText(reversa.toString());

        // Mostrar el número de espacios y palabras en los componentes correspondientes
        txtespacios.setText(String.valueOf(Espacios));
        txtNUM.setText(String.valueOf(Palabras));

        // Contar el número de vocales y mostrar los resultados en el componente "txtvocales"
        int contA = CV(frase, 'a');
        int contE = CV(frase, 'e');
        int contI = CV(frase, 'i');
        int contO = CV(frase, 'o');
        int contU = CV(frase, 'u');
        txtvocales.setText("El número de vocales 'a' es " + contA
                + "\nEl número de vocales 'e' es " + contE
                + "\nEl número de vocales 'i' es " + contI
                + "\nEl número de vocales 'o' es " + contO
                + "\nEl número de vocales 'u' es " + contU);
    }

    private int CV(String frase, char vocal) {
        int cont = 0;
        // Convertir la frase a minúsculas para contar sin distinción entre mayúsculas y minúsculas
        String frase1 = frase.toLowerCase();

        // Iterar sobre cada caracter de la frase
        for (int i = 0; i < frase1.length(); i++) {
            char caracter = frase1.charAt(i);
            // Verificar si el caracter es la vocal específica
            if (caracter == vocal) {
                cont++;
            }
        }

        return cont;

    }//GEN-LAST:event_btnvalidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambiasletras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambiasletras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambiasletras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cambiasletras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambiasletras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvalidar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblE1;
    private javax.swing.JLabel lblE2;
    private javax.swing.JLabel lblE3;
    private javax.swing.JLabel lblfrace;
    private javax.swing.JLabel lblvocales;
    private javax.swing.JTextField txtNUM;
    private javax.swing.JTextField txtalrevez;
    private javax.swing.JTextField txtcambiar;
    private javax.swing.JTextField txtespacios;
    private javax.swing.JTextField txtoracion;
    private javax.swing.JTextArea txtvocales;
    // End of variables declaration//GEN-END:variables

  
}
